swagger: "2.0"
info:
    title: Bank Argent API documentation
    description: Brain storming on the futur api for transactions
    version: 1.0.0
    termsOfService: "https://smartbear.com/terms-of-use/"
host: localhost:3001
basePath: /api/v2
schemes:
    - http
paths:
    /user/transactions/:
        post:
            security:
                - Bearer: []
            tags:
                - Transactions Module
            summary: Transactions
            description: API for fetching transactions history for all the user's accounts
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction records retrieved successfully
                    schema:
                        $ref: "#/definitions/FetchedTransactions"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error
securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header

definitions:
    TransactionRecords:
        type: object
        properties:
            accountLabel:
                type: string
            accountBalance:
                type: number
            accountTransactionsHistory:
                type: object
                properties:
                    id:
                        type: string
                    date:
                        type: string
                    description:
                        type: string
                    amount:
                        type: number
                    category:
                        type: string
                    transactionType:
                        type: string
                    notes:
                        type: string
    FetchedTransactions:
        type: object
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    id:
                        type: string
                    email:
                        type: string
                    accounts:
                        type: array
                        items:
                            $ref: "#/definitions/TransactionRecords"
# todo Updated the account POST req to get data with the token security
# todo update the fake service, the mocked data to match the fake API
# todo Implement the API ?
# todo Add the put method to update a transaction
