swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Transaction API  | Retrieve user's transactions' history | Update transaction
  version: 1.0.0
  termsOfService: "https://smartbear.com/terms-of-use/"
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/transactions/:
    post:
      security:
        - Bearer: [ ]
      tags:
        - Transactions Module
      summary: Transactions API
      description: API for fetching transactions history for all the user's accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transaction records retrieved successfully
          schema:
            $ref: "#/definitions/FetchedTransactions"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: [ ]
      tags:
        - Transactions Module
      summary: Transactions API
      description: API for updating a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Update transaction property
          required: true
          schema:
            $ref: "#/definitions/TransactionProps"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/UpdatedTransaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  TransactionProps:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      category:
        type: string
      transactionType:
        type: string
      notes:
        type: string
  TransactionRecords:
    type: object
    properties:
      accountLabel:
        type: string
      accountBalance:
        type: number
      accountTransactionsHistory:
        type: object
        items:
          $ref: "#/definitions/TransactionProps"
  FetchedTransactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
          accounts:
            type: array
            items:
              $ref: "#/definitions/TransactionRecords"
  UpdatedTransaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        items:
          $ref: "#/definitions/TransactionProps"
